version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
